title: Xuanming HUANG's Homepage
page-top-title: Xuanming (Andy) HUANG （黄炫铭）  
top-section-bg-text: WELCOME TO Xuanming HUANG'S HOMEPAGE
home-subtitle: Xuanming (Andy) HUANG&ensp;|&ensp;黄炫铭
copyright-text: '&copy; Xuanming HUANG 2022-2026. All Rights Reserved.'
