title: Xuanming HUANG's Homepage
page-top-title: WELCOME TO Xuanming HUANG'S HOMEPAGE
top-section-bg-text: NEVER GIVE UP
home-subtitle: Xuanming HUANG&ensp;|&ensp;黄炫铭
copyright-text: '&copy; Xuanming HUANG 2022-2026. All Rights Reserved.'
