title: Xuanming HUANG's Homepage
page-top-title: Xuanming HUANG （黄炫铭） Andy 
top-section-bg-text: WELCOME TO Xuanming HUANG'S HOMEPAGE
home-subtitle: Xuanming(Andy) HUANG&ensp;|&ensp;黄炫铭
copyright-text: '&copy; Xuanming HUANG 2022-2026. All Rights Reserved.'
